---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: sampleproduct-1-web

outputs:
  - name: build-output

run:
  path: bash
  args:
    - -exc
    - |
      echo $(pwd)
      echo $(pwd)
      chmod 775 sampleproduct-1-web/mvnw
      sampleproduct-1-web/mvnw -DskipTests=true package
      ls sampleproduct-1-web
      ls sampleproduct-1-web/target
      cp sampleproduct-1-web/manifest.yml build-output
      cp sampleproduct-1-web/target/sampleproduct-1-web-0.0.1.war build-output
      ls build-output
