---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: sampleproduct-1-web

outputs:
  - name: build-output
    path: build-output/
run:
  path: bash
  args:
    - -exc
    - |
      echo $(pwd)
      cd sampleproduct-1-web
      echo $(pwd)
      chmod 775 mvnw
      ./mvnw -DskipTests=true package
