---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: sampleproduct-1-web

outputs:
  - name: build-output

run:
  path: bash
  args:
    - -exc
    - |
      echo $(pwd)
      cd sampleproduct-1-web
      echo $(pwd)
      chmod 775 mvnw
      ./mvnw -DskipTests=true package
      cd
      cd build-output
      cp sampleproduct-1-web/target/sampleproduct-1-web-0.0.1.war  /.
      echo $(ll)