---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: sampleproduct-1-web

outputs:
  - name: build-output

run:
  path: bash
  args:
    - -exc
    - |
      export TERM=${TERM:-dumb}
      echo $(pwd)
      cd sampleproduct-1-web
      echo $(pwd)
      chmod 755 gradlew
      ./gradlew --no-daemon build
      ls
      ls build/libs
      cp build/libs/sampleproduct-1-web-0.0.1.war ../build-output
      cp manifest.yml ../build-output

      ls ../build-output
