bitbucket:
  name: https://github.com/CodeBlueLabs/sampleproduct-1-web.git
  username: OneDigitalAdmin
  password: pass1234
  branch: master

pws:
  url: https://api.run.pivotal.io
  username: onedigitaladmin@cognizant.com
  password: Pass123$
  organization: Autoloan
  space: PALImmersion
  webappurl: https://palimmersionapp.cfapps.io/
slack:
  repository: cfcommunity/slack-notification-resource
  tag: latest
  url: https://hooks.slack.com/services/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
  channel: "#buildroom"
domain:
  name: pcfalm.agileinteractivelab.com
app:
  url: https://onedigital.cognizant.com/codeblue
app:
  url: https://wsfinancialservices.cfapps.io/
  unittest:
    url: http://cognizantagilelab.com/sampleproduct-1-web
    name: sampleproduct-1-web