resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: ((slack.repository))
    tag: ((slack.tag))

resources:
- name: sampleproduct-1-web
  type: git
  source:
    uri: https://github.com/CodeBlueLabs/sampleproduct-1-web.git
    branch: master
    username: OneDigitalAdmin
    password: pass1234

- name: im-notify
  type: slack-notification
  source:
    url: ((slack.url))

- name: deployapp
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: onedigitaladmin@cognizant.com
    password: Pass123$
    organization: Autoloan
    space: PALImmersion
    skip_cert_check: false

jobs:

- name: Unit Test
  serial: true
  plan:
  - get: sampleproduct-1-web
    trigger: true
  - task: unittest
    file: sampleproduct-1-web/ci/compile.yml
    on_success:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Unit Test* completed successfully
    on_failure:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Unit Test* failed with test case failures, check the build log for details
- name: Acceptance Test
  serial: true
  plan:
  - get: sampleproduct-1-web
    passed: ['Unit Test']
    trigger: true
  - task: acceptancetest
    file: sampleproduct-1-web/ci/test.yml
    params:
      SERVICE_NAME: ws_financial_services
      managerurl: ((environment.testresult.url))
      managerusername: ((environment.testresult.username))
      managerpassword: ((environment.testresult.password))
      appname: ((app.unittest.name))
    on_success:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Acceptance Test* completed successfully
          <https://sampleproduct1-ws.cfapps.io/build/spock-reports/index.html| Click here> to view the test report
    on_failure:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Acceptance Test* failed with test case failures, check the build log for details
- name: Build and Deploy
  serial: true
  plan:
  - get: sampleproduct-1-web
    passed: ['Acceptance Test']
    trigger: true
  - task: buildanddeploy
    file: sampleproduct-1-web/ci/build.yml
  - put: deployapp
    params:
      manifest: sampleproduct-1-web/manifest.yml
    on_success:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Build* completed successfully
    on_failure:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Build* failed, check the build log for details
